global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
  - job_name: nifi-rubelagu-test
    sample_limit: 100000
    file_sd_configs:
      - files: [ "/vagrant/prometheus_file_sd.yaml" ]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(java_lang_.*|jvm_threads_state)'
        action: keep

  
